apiVersion: apps/v1
kind: Deployment
metadata:
  name: primerjava-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: primerjava
  template:
    metadata:
      labels:
        app: primerjava
    spec:
      containers:
        - image: pockar/primerjava:2022-12-04-21-27-12
          name: primerjava
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgres://mouse.db.elephantsql.com:5432/moqshrtp
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: moqshrtp
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: KUMULUZEE_DATASOURCES0_PASSWORD
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: primerjava
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: primerjava