version: "3.9"
services:
  server:
    build: .
    container_name: "pockar/primerjava"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    container_name: "BAZA"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tabela1