kumuluzee:
  name: primerjava-service
  version: 1.0.0
  env:
    name: dev
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/db-primerjava
      connection-url: jdbc:postgresql://db-primerjava:5432/primerjava
      username: dbuser
      password: postgres
      max-pool-size: 20