kumuluzee:
  name: dostavljalec-service
  version: 1.0.0
  env:
    name: dev
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/dostavljalecDS
      connection-url: jdbc:postgresql://dostavljalecservice:5432/dostavljalec
      username: postgres
      password: postgres
      max-pool-size: 20