kumuluzee:
  name: primerjava-service
  version: 1.0.0
  env:
    name: dev
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/Baza
      connection-url: jdbc:postgresql://BAZA:5432/tabela1
      username: user
      password: password
      max-pool-size: 20